name: Run CASR

on:
  push:

jobs:
  run-jpf:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '11' ]
    name: Java ${{ matrix.java }} Run CASR

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Install rust and dependencies
      run: | 
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
        sudo apt install gdb lsb-release
    - name: Install casr
      run: |
        cargo install casr
    - name: Generate and Run JPF Configs
      run: |
        find codes/java/ -name "*.java" | while read -r file; do
          # Extract package name from the Java file
          package=$(grep "^package " "$file" | awk '{print $2}' | sed 's/;$//')
          classname=$(basename "$file" .java)
          casr-java -o java.casrep -- java casr/tests/casr_tests/java/$file
        done
