name: Run CASR

on:
  push:

jobs:
  run-jpf:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '11' ]
    name: Java ${{ matrix.java }} Run CASR

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Install rust and dependencies
      run: | 
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y        
        sudo apt install gdb lsb-release
    - name: Install casr
      run: |
        cargo install casr
    - name: Compile Java files
      run: |
        mkdir -p build
        find codes/java/ -name '*.java' | while read -r javafile; do
          javac -d build "$javafile"
        done
    - name: Run CASR
      run: |
        find build -name '*.class' | while read -r classfile; do
          classfile_rel=$(echo "$classfile" | sed "s|build/||;s|/|.|g;s|.class$||")
          echo "Processing $classfile_rel"
          casr-java -o "$classfile.casrep" -- java -cp build "$classfile_rel"
        done
