name: Run JPF with ref

on:
  push:

jobs:
  run-jpf:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '11' ]
    name: Java ${{ matrix.java }} Run JPF

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        sha: 56071225cd99afc901f466c50190825501845101

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Clone jpf-core
      run: |
        git clone https://github.com/javapathfinder/jpf-core.git /tmp/jpf-core
        cd /tmp/jpf-core
        ./gradlew buildJars
        ./gradlew check  
    - name: Run tests
      run: |
        cd /tmp/jpf-core
        ./gradlew buildJars
        ./gradlew check  
    - name: Run tests
      run: |
        cd /tmp/jpf-core
        ./gradlew buildJars
        ./gradlew check  

    - name: Run tests
      run: |
        cd /tmp/jpf-core
        ./gradlew buildJars
        ./gradlew check  

    - name: Run tests
      run: |
        cd /tmp/jpf-core
        ./gradlew buildJars
        ./gradlew check  

    - name: Run tests
      run: |
        cd /tmp/jpf-core
        ./gradlew buildJars
        ./gradlew check  

    - name: Run tests
      run: |
        cd /tmp/jpf-core
        ./gradlew buildJars
        ./gradlew check  

    - name: Run tests
      run: |
        cd /tmp/jpf-core
        ./gradlew buildJars
        ./gradlew check  

    - name: Run tests
      run: |
        cd /tmp/jpf-core
        ./gradlew buildJars
        ./gradlew check  


         
